# Generated by Django 3.1.3 on 2020-12-15 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(unique=True)),
                ('plant', models.TextField()),
                ('kc', models.FloatField()),
                ('area', models.FloatField()),
                ('water_flowrate', models.FloatField()),
                ('water_t1', models.TimeField(default=datetime.time(12, 0))),
                ('last_irrigation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Plantgroups',
                'db_table': 'Plantgroup',
            },
        ),
        migrations.CreateModel(
            name='Transipration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('start_level', models.FloatField()),
                ('last_level', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Pan_data',
                'db_table': 'Pan_data',
            },
        ),
    ]
