# Generated by Django 3.1.3 on 2020-12-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transipration',
            options={'verbose_name_plural': 'Transpiration'},
        ),
        migrations.AlterModelTable(
            name='transipration',
            table='Transpiration',
        ),
    ]
